# Generated by Django 3.0.3 on 2020-02-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(default='+', max_length=1)),
            ],
        ),
    ]
