# Generated by Django 3.0.3 on 2020-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equips', '0002_equipment_issued_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='issued_to',
            field=models.TextField(default='', max_length=10),
        ),
    ]
