# Generated by Django 3.0.3 on 2020-02-21 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Equips', '0003_auto_20200221_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lastIssued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
