# Generated by Django 3.0.3 on 2020-02-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equips', '0005_auto_20200221_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='choice_text',
            new_name='equip_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='votes',
        ),
        migrations.AddField(
            model_name='equipment',
            name='actual_equipment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='issued_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
