# Generated by Django 3.0.3 on 2020-02-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=10, verbose_name='Ref No.')),
                ('desc', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start of booking')),
                ('end_time', models.DateTimeField(verbose_name='End of Booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.RoomResource')),
            ],
        ),
    ]
