# Generated by Django 3.0.3 on 2020-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_blah'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='roll_no',
            field=models.CharField(default='Admin', max_length=20),
        ),
    ]
