# Generated by Django 3.0.3 on 2020-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_roombooking_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomresource',
            name='s_no',
            field=models.CharField(max_length=50, verbose_name='Ref No.'),
        ),
    ]
