# Generated by Django 3.0.3 on 2020-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200222_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
